server {
    listen 80;
    server_name i14a105.p.ssafy.io;

    # 프론트엔드 정적 파일 서빙
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Vue Router의 history 모드 대응
    }

    # 백엔드 API 프록시 설정
    location /api {
        proxy_pass http://eeum-app:8080; # 백엔드 컨테이너 이름과 포트
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}