version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - influxdb

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    volumes:
      - .:/scripts
    entrypoint: /bin/sh
    tty: true
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - BASE_URL=${BASE_URL:-https://i14a105.p.ssafy.io/api}
