# 1. 로컬 환경 설정 (기본값)
spring:
  profiles:
    active: dev
    include: secret

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:

jwt:
  private-key-path: certs/private_key_pkcs8.pem
  public-key-path: certs/public_key.pem
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

logging:
  level:
    org.ssafy.eeum: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

eeum:
  swagger-url: http://localhost:8080

---
# 2. 배포 환경 설정 (프로필 이름: prod)
spring:
  config:
    activate:
      on-profile: prod

server:
  forward-headers-strategy: framework

eeum:
  swagger-url: https://i14a105.p.ssafy.io