spring:
  profiles:
    include: secret

  cloud:
    aws:
      region:
        static: ap-northeast-2

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  private-key-path: certs/private_key_pkcs8.pem
  public-key-path: certs/public_key.pem
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

logging:
  level:
    org.ssafy.eeum: debug
    # 아래 두 줄을 반드시 추가해야 카카오가 왜 화났는지 알 수 있습니다!
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

